apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-postgres
  labels:
    app: payment-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-postgres
  template:
    metadata:
      name: payment-postgres
      labels:
        app: payment-postgres
    spec:
      containers:
        - name: payment-postgres
          image: postgres:15.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: "POSTGRES_PASSWORD"
              value: "payment-manager"
            - name: "POSTGRES_USER"
              value: "economist"
          imagePullPolicy: Always
      restartPolicy: Always
      