apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigateway
automountServiceAccountToken: true