targetSystem: "linux"
datadog:
  logs:
    enabled: true
    containerCollectAll: true
  networkMonitoring:
    enabled: true
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.com
