apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-service
  labels:
    app: shipment-service
    tags.datadoghq.com/env: Production
    tags.datadoghq.com/service: shipment-service
    tags.datadoghq.com/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipment-service
  template:
    metadata:
      name: shipment-service
      labels:
        app: shipment-service
        tags.datadoghq.com/env: Production
        tags.datadoghq.com/service: shipment-service
        tags.datadoghq.com/version: 1.0.0
        admission.datadoghq.com/enabled: "true"
      annotations:
          admission.datadoghq.com/dotnet-lib.version: v2.38.0
    spec:
      containers:
        - name: shipment-service
          image: mqsr/coffeespace-shipment-service:2.0.0
          imagePullPolicy: Always
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          - name: "AZURE_CLIENT_ID"
            valueFrom:
              secretKeyRef:
                key: "azure-client-id"
                name: "azure-key-vault"
          - name: "AZURE_CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                key: "azure-client-secret"
                name: "azure-key-vault"
          - name: "AZURE_TENANT_ID"
            valueFrom:
              secretKeyRef:
                key: "azure-tenant-id"
                name: "azure-key-vault"
          - name: "AZURE_VAULT_NAME"
            valueFrom:
              secretKeyRef:
                key: "azure-vault-name"
                name: "azure-key-vault"
          - name: "DD_API_KEY"
            valueFrom:
              secretKeyRef:
                key: "api-key"
                name: "datadog-secret"
      restartPolicy: Always
      