apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
  labels:
    app: ordering-api
    tags.datadoghq.com/env: Production
    tags.datadoghq.com/service: ordering-api
    tags.datadoghq.com/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      name: ordering-api
      labels:
        app: ordering-api
        tags.datadoghq.com/env: Production
        tags.datadoghq.com/service: ordering-api
        tags.datadoghq.com/version: 1.0.0
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: v2.38.0
    spec:
      containers:
        - name: ordering-api
          image: mqsr/coffeespace-ordering-api:2.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Production"
            - name: "AZURE_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key: "azure-client-id"
                  name: "azure-key-vault"
            - name: "AZURE_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key: "azure-client-secret"
                  name: "azure-key-vault"
            - name: "AZURE_TENANT_ID"
              valueFrom:
                secretKeyRef:
                  key: "azure-tenant-id"
                  name: "azure-key-vault"
            - name: "AZURE_VAULT_NAME"
              valueFrom:
                secretKeyRef:
                  key: "azure-vault-name"
                  name: "azure-key-vault"
            - name: "DD_API_KEY"
              valueFrom:
                secretKeyRef:
                  key: "api-key"
                  name: "datadog-secret"
      restartPolicy: Always
