apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    tags.datadoghq.com/env: Production
    tags.datadoghq.com/service: redis
    tags.datadoghq.com/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
        tags.datadoghq.com/env: Production
        tags.datadoghq.com/service: redis
        tags.datadoghq.com/version: 1.0.0
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: redis
          image: redis:alpine3.18
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
      restartPolicy: Always
      