name: Build CoffeeSpace project

on:
  push:
    branches:
      - main
      - wip
  pull_request:
    branches:
      - main

jobs:
  OrderingApi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Restore dependencies
      run: dotnet restore CoffeeSpace.OrderingApi/CoffeeSpace.OrderingApi.csproj --no-restore
      
    - name: Build and test
      run: dotnet build --configuration Release CoffeeSpace.OrderingApi/CoffeeSpace.OrderingApi.csproj --no-restore
